title: "AIDA Prompt Marketplace"
description: "A curated collection of AI prompts, easily searchable and shareable. Built with Jekyll and hosted on GitHub Pages."
baseurl: "" # Adjust if using a subpath
url: "http://localhost:4000" # Adjust for production

collections:
  prompts:
    output: true

# Exclude files you don't want Jekyll to process
exclude:
  - README.md

# Include any additional settings as needed