---
name: 📖 Prompt for AIDA Marketplace
description: Template for generating a prompt in the AIDA Marketplace.
title: "{{ prompt_name }}"
labels: [prompt]
assignees: []

body:
  - type: input
    id: prompt_name
    attributes:
      label: Prompt Name
      description: Enter the prompt name (used for file naming).
      placeholder: "Diversity inclusion text enhancer"
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author
      description: Enter your name.
      placeholder: "John Doe"
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Provide relevant tags (comma-separated).
      placeholder: "diversity, text, enhancer"
    validations:
      required: true

  - type: textarea
    id: prompt
    attributes:
      label: Prompt
      description: The raw prompt text.
      placeholder: |
        Given a text, enhance it to be more inclusive and diverse.
        - Do not use offensive words or phrases.
        - Do not use words or phrases that are not inclusive or diverse.
        - Do it in a way that it sounds natural and not forced.
        Text to enhance:

        \`\`\`
        [TEXT]
        \`\`\`
      render: yaml  # This will render it in a code block.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        title: "{{ prompt_name }}"
        author: "{{ author }}"
        tags: [{{ tags }}]
        ---

        {{ prompt }}
