title: "AIDA Prompt Marketplace"
description: "A curated collection of AI prompts, easily searchable and shareable. Built with Jekyll and hosted on GitHub Pages."
baseurl: "/asset-prompting-marketplace" # Adjust if using a subpath
url: "https://erni-academy.github.io" # Adjust for production

collections:
  prompts:
    output: true

# Exclude files you don't want Jekyll to process
exclude:
  - README.md

# Include any additional settings as needed