name: Issue to PR Automation

on:
  issues:
    types: [opened]
    filters:
      labels:
        - 'prompt'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git Config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create Branch
        id: branch_name
        run: |
          BRANCH_NAME="issue-${{ github.event.issue.number }}"
          echo "::set-output name=branch::$BRANCH_NAME"
          git checkout -b $BRANCH_NAME

      - name: Create File from Issue
        run: |
          echo '${{ toJson(github.event.issue.body) }}' | jq -r '.' > "issue-${{ github.event.issue.number }}.md"
          git add .
          git commit -m "Add issue content for #${{ github.event.issue.number }}"

      - name: Push Branch
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.branch_name.outputs.branch }}
          title: "PR for Issue #${{ github.event.issue.number }}"
          body: |
            This pull request addresses Issue #${{ github.event.issue.number }}.
            Automatically generated by GitHub Actions.
