name: Issue to PR Automation

on:
  issues:
    types: [opened]

jobs:
  create_pr:
    if: contains( toJson( github.event.issue.labels ), '"prompt"' )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git Config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Extract Issue Data
        id: extract_data
        run: |
          echo "Extracting data from issue body"

          # Set PROMPT_NAME to the issue title
          prompt_name="${{ github.event.issue.title }}"
          echo "PROMPT_NAME=$prompt_name" >> $GITHUB_ENV

          # Save the issue body into a variable safely
          issue_body=$(printf '%s' "${{ github.event.issue.body }}")

          # Extract author
          author="$(printf '%s' "$issue_body" \
            | awk '/^### Author$/,/^###/{if ($0 !~ /^###/ && $0 != "") print}' \
            | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
          echo "AUTHOR=$author" >> $GITHUB_ENV

          # Extract tags
          tags="$(printf '%s' "$issue_body" \
            | awk '/^### Tags$/,/^###/{if ($0 !~ /^###/ && $0 != "") print}' \
            | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
          echo "TAGS=$tags" >> $GITHUB_ENV

          # Extract prompt content
          prompt_content="$(printf '%s' "$issue_body" \
            | awk '/^### Prompt$/,/^###/{if ($0 !~ /^###/ && $0 != "") print}')"
          echo "PROMPT_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$prompt_content" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Branch
        id: branch_name
        run: |
          BRANCH_NAME="issue-${{ github.event.issue.number }}"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
          git checkout -b "$BRANCH_NAME"

      - name: Debug Extracted Data
        run: |
          echo "Prompt Name: $PROMPT_NAME"
          echo "Author: $AUTHOR"
          echo "Tags: $TAGS"
          echo "Prompt Content:"
          echo "$PROMPT_CONTENT"

      - name: Create File from Issue
        run: |
          # Sanitize prompt name to create a valid file name
          FILE_NAME="$(echo "$PROMPT_NAME" | tr '[:upper:]' '[:lower:]' \
            | sed -E 's/[^a-z0-9]+/-/g; s/^-+|-+$//g')"
          FILE_PATH="aida-prompts/_prompts/${FILE_NAME}.md"

          echo "Creating file at $FILE_PATH"

          mkdir -p "$(dirname "$FILE_PATH")"

          # Use printf to write to the file
          printf '%s\n' \
            '---' \
            "title: \"$PROMPT_NAME\"" \
            "author: \"$AUTHOR\"" \
            "tags: [$TAGS]" \
            '---' \
            '' \
            "$PROMPT_CONTENT" \
            > "$FILE_PATH"

          git add "$FILE_PATH"
          git commit -m "Add prompt '$PROMPT_NAME' from Issue #${{ github.event.issue.number }}"

      - name: Push Branch
        run: |
          git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.branch_name.outputs.branch }}
          base: main
          title: "Add Prompt: $PROMPT_NAME"
          body: |
            Adds a new prompt from Issue #${{ github.event.issue.number }}.
            Automatically generated by GitHub Actions.
